# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, '3.10']
    
    services:
      typecho:
        image: joyqi/typecho:1.2.0-php8.0-apache
        env:
          TYPECHO_DB_ADAPTER: Pdo_SQLite
          TYPECHO_INSTALL: 1
          TYPECHO_SITE_URL: http://127.0.0.1
          TYPECHO_USER_NAME: typecho
          TYPECHO_USER_PASSWORD: testpassword
        ports:
          - 80:80

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test
      env:
        XMLRPC_URL: http://127.0.0.1/index.php/action/xmlrpc
        XMLRPC_USER_NAME: typecho
        XMLRPC_USER_PASSWORD: testpassword
      run: |
        python -m unittest discover -s tests
